spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  password: 9030009470
  url: jdbc:mysql://localhost:3306/cart_management
  username: root
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
 
